---

- name: installing minikube
  connection: local
  hosts: localhost
  become: yes
  pre_tasks:
    - name: install jmespath for minikube installation
      pip:
       name: jmespath
  roles:
    - name: githubixx.kubectl
      src: https://github.com/githubixx/ansible-role-kubectl.git
      version: 24.0.1+1.33.5
    - role: kameshsampath.minikube