on:
  workflow_dispatch:
    inputs:
      site_name:
        description: 'name of the site'
        required: false
        type: string

jobs:
  devops-interview:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      # Prepare the Runner
      - run: ansible-playbook --connection=local --inventory localhost, ansible/site.yml
      # Start Kubernetes

      # Deploy the Application
      - run: helm template test ./helm