on:
  workflow_dispatch:
    inputs:
      site_name:
        description: 'name of the site'
        required: false
        type: string

jobs:
  Prepare-the-Runner:
    runs-on: ubuntu-latest
    steps:
    - run: ls
    - run: pwd
    - run: ansible-playbook --connection=local --inventory localhost, ansible/site.yml